# site settings
title: Tiercel Foundry
subtitle: 
email: 
description: Home of Tiercel Foundry games
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 
city: Seattle
state: WA
zip_code: 98117
country: United States of America
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/tiercelfoundry
  GitLab:
  Instagram:
  LinkedIn:
  Twitter:
  BlueSky: https://bsky.app/profile/grahame.fyi
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
